src/objects/EFCell__c.object
<CustomObject>
    <fields>
        <fullName>EFRow__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>EF Row</label>
        <referenceTo>EFRow__c</referenceTo>
        <relationshipLabel>EF Cells</relationshipLabel>
        <relationshipName>EFCells</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EFStyle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EF Style</label>
        <referenceTo>EFStyle__c</referenceTo>
        <relationshipLabel>EF Cells</relationshipLabel>
        <relationshipName>EFCells</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EF Cell</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EF Cells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EFRow__c.object
<CustomObject>
    <fields>
        <fullName>EFStyle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>EF Style</label>
        <referenceTo>EFStyle__c</referenceTo>
        <relationshipLabel>EF Rows</relationshipLabel>
        <relationshipName>EFRows</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>EF Row</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EF Rows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EFStyle__c.object
<CustomObject>
    <fields>
        <fullName>AlignmentHorizontal__c</fullName>
        <label>Alignment Horizontal</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>left</fullName>
                    <default>true</default>
                    <label>left</label>
                </value>
                <value>
                    <fullName>center</fullName>
                </value>
                <value>
                    <fullName>right</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AlignmentVertical__c</fullName>
        <label>Alignment Vertical</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>bottom</fullName>
                    <default>true</default>
                    <label>bottom</label>
                </value>
                <value>
                    <fullName>middle</fullName>
                </value>
                <value>
                    <fullName>top</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BorderBottom__c</fullName>
        <label>Border Bottom</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>thin</fullName>
                </value>
                <value>
                    <fullName>dotted</fullName>
                </value>
                <value>
                    <fullName>dashDot</fullName>
                </value>
                <value>
                    <fullName>hair</fullName>
                </value>
                <value>
                    <fullName>dashDotDot</fullName>
                </value>
                <value>
                    <fullName>slantDashDot</fullName>
                </value>
                <value>
                    <fullName>mediumDashed</fullName>
                </value>
                <value>
                    <fullName>mediumDashDotDot</fullName>
                </value>
                <value>
                    <fullName>mediumDashDot</fullName>
                </value>
                <value>
                    <fullName>medium</fullName>
                </value>
                <value>
                    <fullName>double</fullName>
                </value>
                <value>
                    <fullName>thick</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BorderColor__c</fullName>
        <label>Border Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BorderLeft__c</fullName>
        <label>Border Left</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>thin</fullName>
                </value>
                <value>
                    <fullName>dotted</fullName>
                </value>
                <value>
                    <fullName>dashDot</fullName>
                </value>
                <value>
                    <fullName>hair</fullName>
                </value>
                <value>
                    <fullName>dashDotDot</fullName>
                </value>
                <value>
                    <fullName>slantDashDot</fullName>
                </value>
                <value>
                    <fullName>mediumDashed</fullName>
                </value>
                <value>
                    <fullName>mediumDashDotDot</fullName>
                </value>
                <value>
                    <fullName>mediumDashDot</fullName>
                </value>
                <value>
                    <fullName>medium</fullName>
                </value>
                <value>
                    <fullName>double</fullName>
                </value>
                <value>
                    <fullName>thick</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BorderRight__c</fullName>
        <label>Border Right</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>thin</fullName>
                </value>
                <value>
                    <fullName>dotted</fullName>
                </value>
                <value>
                    <fullName>dashDot</fullName>
                </value>
                <value>
                    <fullName>hair</fullName>
                </value>
                <value>
                    <fullName>dashDotDot</fullName>
                </value>
                <value>
                    <fullName>slantDashDot</fullName>
                </value>
                <value>
                    <fullName>mediumDashed</fullName>
                </value>
                <value>
                    <fullName>mediumDashDotDot</fullName>
                </value>
                <value>
                    <fullName>mediumDashDot</fullName>
                </value>
                <value>
                    <fullName>medium</fullName>
                </value>
                <value>
                    <fullName>double</fullName>
                </value>
                <value>
                    <fullName>thick</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BorderTop__c</fullName>
        <label>Border Top</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>thin</fullName>
                </value>
                <value>
                    <fullName>dotted</fullName>
                </value>
                <value>
                    <fullName>dashDot</fullName>
                </value>
                <value>
                    <fullName>hair</fullName>
                </value>
                <value>
                    <fullName>dashDotDot</fullName>
                </value>
                <value>
                    <fullName>slantDashDot</fullName>
                </value>
                <value>
                    <fullName>mediumDashed</fullName>
                </value>
                <value>
                    <fullName>mediumDashDotDot</fullName>
                </value>
                <value>
                    <fullName>mediumDashDot</fullName>
                </value>
                <value>
                    <fullName>medium</fullName>
                </value>
                <value>
                    <fullName>double</fullName>
                </value>
                <value>
                    <fullName>thick</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FillColor__c</fullName>
        <label>FillColor</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FillPatern__c</fullName>
        <label>Fill Patern</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>none</fullName>
                    <default>true</default>
                    <label>none</label>
                </value>
                <value>
                    <fullName>solid</fullName>
                </value>
                <value>
                    <fullName>darkGray</fullName>
                </value>
                <value>
                    <fullName>mediumGray</fullName>
                </value>
                <value>
                    <fullName>lightGray</fullName>
                </value>
                <value>
                    <fullName>gray125</fullName>
                </value>
                <value>
                    <fullName>gray0625</fullName>
                </value>
                <value>
                    <fullName>darkHorizontal</fullName>
                </value>
                <value>
                    <fullName>darkVertical</fullName>
                </value>
                <value>
                    <fullName>darkDown</fullName>
                </value>
                <value>
                    <fullName>darkUp</fullName>
                </value>
                <value>
                    <fullName>darkGrid</fullName>
                </value>
                <value>
                    <fullName>darkTrellis</fullName>
                </value>
                <value>
                    <fullName>lightHorizontal</fullName>
                </value>
                <value>
                    <fullName>lightVertical</fullName>
                </value>
                <value>
                    <fullName>lightDown</fullName>
                </value>
                <value>
                    <fullName>lightUp</fullName>
                </value>
                <value>
                    <fullName>lightGrid</fullName>
                </value>
                <value>
                    <fullName>lightTrellis</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FontBold__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Font Bold</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FontColor__c</fullName>
        <label>Font Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FontItalic__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Font Italic</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FontSize__c</fullName>
        <defaultValue>12</defaultValue>
        <label>Font Size</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FontUnderline__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Font Underline</label>
        <type>Checkbox</type>
    </fields>
    <label>EF Style</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EF Styles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EFStyleSelector.cls
/** 
Copyright (c) 2022, CloudBudget, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:
* Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.
* Neither the name of the CloudBudget, Inc. nor the names of its contributors
may be used to endorse or promote products derived from this software
without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

 */


public with sharing class EFStyleSelector {

	@AuraEnabled
	public static EFStyle__c getEFStyleByIdServer(String tId) {
		return [
				SELECT
						AlignmentHorizontal__c,
						AlignmentVertical__c,
						BorderBottom__c,
						BorderColor__c,
						BorderLeft__c,
						BorderRight__c,
						BorderTop__c,
						FillColor__c,
						FillPatern__c,
						FontBold__c,
						FontColor__c,
						FontItalic__c,
						FontSize__c,
						FontUnderline__c,
						Id,
						Name
				FROM EFStyle__c
				WHERE Id = :tId
		];
	}

	@AuraEnabled
	public static List<EFStyle__c> getAllEFStylesByTemplateIdServer(String tId) {
		Set<Id> styleIds = new Set<Id>();
		for (EFCell__c cell : EFCellSelector.getAllEFCellsByTemplateIdServer(tId)) {
			System.debug('cell.EFStyle__c = ' + cell.EFStyle__c);
			if (cell.EFStyle__c != null) styleIds.add(cell.EFStyle__c);
		}
		for (EFRow__c row : EFRowSelector.getAllEFRowsByTemplateIdServer(tId)) {
			if (row.EFStyle__c != null) styleIds.add(row.EFStyle__c);
		}
		System.debug('styleIds = ' + styleIds);
		return [
				SELECT AlignmentHorizontal__c,
						AlignmentVertical__c,
						BorderBottom__c,
						BorderColor__c,
						BorderLeft__c,
						BorderRight__c,
						BorderTop__c,
						FillColor__c,
						FillPatern__c,
						FontBold__c,
						FontColor__c,
						FontItalic__c,
						FontSize__c,
						FontUnderline__c,
						Id,
						Name
				FROM EFStyle__c
				WHERE Id IN:styleIds
				LIMIT 5000
		];
	}
}